[package]
name = "capter"
version = "2.2.2"
description = "A simple cross-platform screenshot tool"
edition = "2021"
authors = ["decipher3114 <decipher3114@gmail.com>"]
build = "build.rs"

[dependencies]
active-win-pos-rs = "0.8"
arboard = { version = "3.4", features = ["wayland-data-control", "wl-clipboard-rs"] }
chrono = "0.4"
iced = { version = "0.13", features = ["advanced", "canvas", "multi-window", "image", "tokio"] }
iced_anim = { version = "0.1", features = ["derive", "serde"] }
indexmap = "2.6"
interprocess = { version = "2.2", features = ["tokio"] }
mouse_position = "0.1"
rdev = { git = "https://github.com/rustdesk-org/rdev", branch = "master"}
rfd = { version = "0.14" }
serde = { version = "1.0", features = ["derive"] }
tiny-skia = "0.11"
tokio = { version = "1.40", features = ["full", "rt"] }
toml = "0.8"
tray-icon = "0.17"
xcap = "0.0"

[target.'cfg( target_os = "linux" )'.dependencies]
gtk = "0.18"

[target.'cfg( target_os = "windows" )'.build-dependencies]
winresource = "0.1"

[package.metadata.winresource]
ProductName = "Capter"
FileDescription = "Capter"

[package.metadata.packager]
product-name = "Capter"
identifier = "app.decipher.capter"
authors = ["decipher3114 <decipher3114@gmail.com>"]
publisher = "decipher3114"
category = "Utility"
copyright = "Copyright © 2024"
formats = ["wix", "deb", "dmg", "rpm"]
before-packaging-command = "cargo build --release"
icons = ["assets/resources/windows/icon.ico", "assets/resources/macos/icon.icns", "assets/resources/linux/hicolor/*/apps/capter.png"]
out-dir = "target/packages"

[package.metadata.packager.wix]
banner-path = "assets/images/wix_banner.png"
dialog-image-path = "assets/images/dialog_image.png"

[package.metadata.packager.windows]
digest-algorithim = "SHA256"
certificate-thumbprint = "07a9c417660868a4420fe9e2f8b6ac2e1a33228a"
tsp = true
timestamp-url = "http://timestamp.digicert.com"

[package.metadata.packager.macos]
minimum-system-version = "10.13"

[package.metadata.packager.deb]
depends = ["libgtk-3-dev", "libxdo-dev", "libayatana-appindicator3-dev", "libxcb1", "libxrandr2", "libdbus-1-3"]

[package.metadata.packager.rpm]
name = "capter"
version = "2.2.2"
release = 1
license = "MIT"
summary = "A simple cross-platform screenshot tool"
description = "Capter is a lightweight, cross-platform tool for capturing screenshots and managing screen content with ease."
homepage = "https://yourhomepage.com"
changelog = "CHANGELOG.md"
requires = ["gtk3", "libxcb", "libxrandr", "dbus", "xdo"]
